"""Blender integration and interchange export utilities for OpenBiomech (mkvis3d).

Provides direct export of motion trials and kinematic skeleton models to:
1. Standalone Blender Python script (.py) that generates empties, armatures, materials, and keyframed animation.
2. Standard Biovision Hierarchy (.bvh) mocap files importable by Blender's native BVH importer.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np

from .biomech_math.lcs import compute_lcs_matrix
from .marker_trial import MarkerTrial

# mkvis3d/vailá trials use the ISB laboratory convention (X=ML, Y=AP/forward,
# Z=vertical/up) — see biomech_math.lcs.LCS_PRESETS["isb_default"]. The BVH
# format (and Blender's native BVH importer) instead expects Y=up, Z=forward,
# X=right. Writing ISB xyz straight into Xposition/Yposition/Zposition
# channels put the subject's vertical axis into BVH's forward channel, so the
# mocap loaded on its side / facing the wrong way in Blender's 3D viewport.
# Reuse the LCS rotation machinery to convert ISB -> BVH axes before writing,
# instead of re-deriving the mapping. This is a -90 degree rotation about X
# (x, y, z) -> (x, z, -y): X unchanged, ISB's up (Z) becomes BVH's up (Y),
# ISB's forward (Y) becomes BVH's forward (Z) with the sign flip needed to
# keep the rotation right-handed. Cross-checked against data/rec3d_*.bvh, a
# same-trial reference export already known to load correctly in Blender.
_ISB_TO_BVH_ROTATION, _ = compute_lcs_matrix(ap_direction="+Z", axial_direction="-Y")


def generate_blender_python_script(
    trial: MarkerTrial,
    name: str = "trial",
    skeleton_template: dict[str, Any] | None = None,
    marker_radius: float = 0.015,
) -> str:
    """Generate a self-contained Python script to be executed inside Blender.

    Can be run via `blender --python script.py` or inside Blender's Text Editor.
    Creates:
    - Target frame rate and timeline duration matching trial metadata.
    - Dedicated Blender collection `OpenBiomech_<name>`.
    - Keyframed Empty / Sphere objects for all valid marker trajectories.
    - If a skeleton template is provided, creates an Armature with connected Bones
      and automated Stretch-To / Copy-Location tracking constraints.
    """
    labels = list(trial.labels)
    rate_hz = float(trial.rate_hz) if np.isfinite(trial.rate_hz) and trial.rate_hz > 0 else 100.0
    fps = int(round(rate_hz))
    num_frames = len(trial.xyz)

    # Clean name for Blender objects
    safe_name = "".join(c if c.isalnum() or c in ("_", "-") else "_" for c in name)

    # Prepare trajectory data as compact JSON string
    # Replace NaN/inf with None for JSON serialization
    clean_xyz = []
    for frame_pts in trial.xyz:
        frame_list = []
        for pt in frame_pts:
            if np.all(np.isfinite(pt)):
                frame_list.append(
                    [round(float(pt[0]), 5), round(float(pt[1]), 5), round(float(pt[2]), 5)]
                )
            else:
                frame_list.append(None)
        clean_xyz.append(frame_list)

    # Skeleton connections: resolve template tokens (pN, 0- or 1-based
    # auto-detected, or plain marker names) to this trial's labels.
    from .skeleton import classify_template_connections

    bones = []
    if skeleton_template:
        template = dict(skeleton_template)
        if not template.get("connections"):
            template["connections"] = skeleton_template.get("bones") or []
        conns = classify_template_connections(template, labels)
        zero_based = any(str(t).lower() == "p0" for c in conns for t in c["connection"]) or (
            "0-based" in str(template.get("note", ""))
        )

        def to_label(token: str) -> str | None:
            if token in labels:
                return token
            if token.lower().startswith("p") and token[1:].isdigit():
                idx = int(token[1:]) - (0 if zero_based else 1)
                if 0 <= idx < len(labels):
                    return labels[idx]
            return None

        for c in conns:
            la, lb = to_label(c["connection"][0]), to_label(c["connection"][1])
            if la is not None and lb is not None:
                bones.append((la, lb, c["side"]))

    script_template = f"""# Auto-generated by OpenBiomech (mkvis3d)
# Compatible with Blender 3.x, 4.x, and 5.x
import bpy
import mathutils

def setup_openbiomech_scene():
    print("[OpenBiomech] Importing trial '{safe_name}'...")

    # 1. Timeline and Units Configuration
    scene = bpy.context.scene
    scene.render.fps = {fps}
    scene.frame_start = 1
    scene.frame_end = {num_frames}
    scene.unit_settings.system = 'METRIC'
    scene.unit_settings.scale_length = 1.0

    # 2. Collection
    coll_name = "OpenBiomech_{safe_name}"
    coll = bpy.data.collections.get(coll_name)
    if not coll:
        coll = bpy.data.collections.new(coll_name)
        bpy.context.scene.collection.children.link(coll)

    # 3. Trajectory Data
    labels = {json.dumps(labels)}
    trajectory_data = {json.dumps(clean_xyz)}
    num_frames = len(trajectory_data)
    num_markers = len(labels)

    # 4. Marker Material
    mat_marker = bpy.data.materials.get("OpenBiomech_MarkerMat")
    if not mat_marker:
        mat_marker = bpy.data.materials.new("OpenBiomech_MarkerMat")
        mat_marker.use_nodes = True
        bsdf = mat_marker.node_tree.nodes.get("Principled BSDF")
        if bsdf:
            if "Base Color" in bsdf.inputs:
                bsdf.inputs["Base Color"].default_value = (0.35, 0.87, 0.76, 1.0)
            if "Emission Color" in bsdf.inputs:
                bsdf.inputs["Emission Color"].default_value = (0.35, 0.87, 0.76, 1.0)

    # 5. Create Marker Empties
    marker_objects = {{}}
    for label in labels:
        obj_name = f"OB_{{label}}"
        obj = bpy.data.objects.get(obj_name)
        if not obj:
            obj = bpy.data.objects.new(obj_name, None)
            obj.empty_display_type = 'SPHERE'
            obj.empty_display_size = {marker_radius}
            coll.objects.link(obj)
        marker_objects[label] = obj

    # 6. Apply Keyframed Coordinates
    for f_idx, frame_pts in enumerate(trajectory_data):
        blender_frame = f_idx + 1
        for m_idx, pt in enumerate(frame_pts):
            if pt is not None:
                lbl = labels[m_idx]
                obj = marker_objects[lbl]
                # Blender uses right-handed Z-up: (X, Y, Z)
                obj.location = (pt[0], pt[1], pt[2])
                obj.keyframe_insert(data_path="location", frame=blender_frame)

    print(f"[OpenBiomech] Keyframed {{num_markers}} markers over {{num_frames}} frames.")

    # 7. Build Skeleton Armature (if provided)
    bones_config = {json.dumps(bones)}
    if bones_config:
        armature_name = "OpenBiomech_Skeleton_{safe_name}"
        arm_data = bpy.data.armatures.new(armature_name)
        arm_obj = bpy.data.objects.new(armature_name, arm_data)
        coll.objects.link(arm_obj)
        bpy.context.view_layer.objects.active = arm_obj
        bpy.ops.object.mode_set(mode='EDIT')

        first_frame = trajectory_data[0]
        created_bones = []
        for b_entry in bones_config:
            j_a, j_b = b_entry[0], b_entry[1]
            b_side = b_entry[2] if len(b_entry) > 2 else "center"
            # Resolve marker positions at frame 0
            pos_a, pos_b = None, None
            if j_a in marker_objects and j_b in marker_objects:
                obj_a = marker_objects[j_a]
                obj_b = marker_objects[j_b]
                # Try finding initial positions
                for f_pts in trajectory_data:
                    idx_a = labels.index(obj_a.name.replace("OB_", "")) if obj_a.name.replace("OB_", "") in labels else -1
                    idx_b = labels.index(obj_b.name.replace("OB_", "")) if obj_b.name.replace("OB_", "") in labels else -1
                    if idx_a >= 0 and idx_b >= 0 and f_pts[idx_a] is not None and f_pts[idx_b] is not None:
                        pos_a = mathutils.Vector(f_pts[idx_a])
                        pos_b = mathutils.Vector(f_pts[idx_b])
                        break

            if pos_a is not None and pos_b is not None:
                bone_name = f"Bone_{{j_a}}_{{j_b}}"
                edit_bone = arm_data.edit_bones.new(bone_name)
                edit_bone.head = pos_a
                edit_bone.tail = pos_b
                created_bones.append((bone_name, j_a, j_b, b_side))

        bpy.ops.object.mode_set(mode='POSE')
        bone_colors = {{
            "left": (0.0, 1.0, 0.0),    # Green (0, 255, 0)
            "right": (1.0, 0.5, 0.0),   # Orange (255, 128, 0)
            "center": (0.2, 0.6, 1.0),  # Blue (51, 153, 255)
        }}
        # Add Stretch-To and Copy-Location constraints so bones track markers
        for bone_name, j_a, j_b, b_side in created_bones:
            pose_bone = arm_obj.pose.bones.get(bone_name)
            if pose_bone and j_a in marker_objects and j_b in marker_objects:
                c_loc = pose_bone.constraints.new(type='COPY_LOCATION')
                c_loc.target = marker_objects[j_a]
                c_track = pose_bone.constraints.new(type='STRETCH_TO')
                c_track.target = marker_objects[j_b]
                if hasattr(pose_bone, "color"):
                    try:
                        pose_bone.color.palette = 'CUSTOM'
                        c = bone_colors.get(b_side, bone_colors["center"])
                        pose_bone.color.custom.normal = c
                        pose_bone.color.custom.select = (min(1.0, c[0] * 1.2), min(1.0, c[1] * 1.2), min(1.0, c[2] * 1.2))
                    except Exception:
                        pass

        print(f"[OpenBiomech] Built armature with {{len(created_bones)}} bones.")

    print("[OpenBiomech] Import complete! Press Space in Blender to play motion.")

if __name__ == "__main__":
    setup_openbiomech_scene()
"""
    return script_template


def export_blender_script(
    trial: MarkerTrial,
    output_path: Path | str,
    skeleton_template: dict[str, Any] | None = None,
    name: str | None = None,
) -> Path:
    """Export a motion trial as a runnable Blender Python script (.py)."""
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    trial_name = name or out.stem.replace("_blender", "")
    code = generate_blender_python_script(
        trial=trial,
        name=trial_name,
        skeleton_template=skeleton_template,
    )
    out.write_text(code, encoding="utf-8")
    return out


def export_bvh(
    trial: MarkerTrial,
    output_path: Path | str,
    name: str = "trial",
) -> Path:
    """Export motion trial to standard Biovision Hierarchy (.bvh) mocap file.

    Blender can import this natively via `bpy.ops.import_anim.bvh(filepath=...)`.

    Trial coordinates are assumed to be in the ISB laboratory convention
    (X=ML, Y=AP/forward, Z=up — see `biomech_math.lcs.LCS_PRESETS`) and are
    rotated to the BVH convention (X=right, Y=up, Z=forward) before being
    written, so the file's Xposition/Yposition/Zposition channels land the
    subject upright and facing forward when imported into Blender.
    """
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    labels = list(trial.labels)
    rate_hz = float(trial.rate_hz) if np.isfinite(trial.rate_hz) and trial.rate_hz > 0 else 100.0
    frame_time = 1.0 / rate_hz
    num_frames = len(trial.xyz)
    xyz_bvh = np.einsum("ij,fmj->fmi", _ISB_TO_BVH_ROTATION, trial.xyz)

    lines = ["HIERARCHY"]
    for label in labels:
        lines.append(f"ROOT {label}")
        lines.append("{")
        lines.append("\tOFFSET 0.000000 0.000000 0.000000")
        lines.append("\tCHANNELS 3 Xposition Yposition Zposition")
        lines.append("\tEnd Site")
        lines.append("\t{")
        lines.append("\t\tOFFSET 0.000000 0.000000 0.000000")
        lines.append("\t}")
        lines.append("}")

    lines.append("MOTION")
    lines.append(f"Frames: {num_frames}")
    lines.append(f"Frame Time: {frame_time:.8f}")

    # Track last known valid position for markers with missing frames
    last_valid = [np.array([0.0, 0.0, 0.0], dtype=np.float64) for _ in labels]
    # Initialize with first valid
    for frame_pts in xyz_bvh:
        for idx, pt in enumerate(frame_pts):
            if np.all(np.isfinite(pt)):
                last_valid[idx] = np.array(pt, dtype=np.float64)

    for frame_pts in xyz_bvh:
        frame_vals = []
        for idx, pt in enumerate(frame_pts):
            if np.all(np.isfinite(pt)):
                pos = pt
                last_valid[idx] = np.array(pt, dtype=np.float64)
            else:
                pos = last_valid[idx]
            frame_vals.extend([f"{pos[0]:.6f}", f"{pos[1]:.6f}", f"{pos[2]:.6f}"])
        lines.append(" ".join(frame_vals))

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out
