"use strict";
const $ = id => document.getElementById(id);
const boot = JSON.parse($("trial-data").textContent);
const token = location.hash.slice(1);
let trial=null, frame=0, playing=false, lastTick=0, elapsed=0, yaw=-.45, pitch=.22, zoom=1, pan=[0,0], center=[0,0,0], span=1, distances=[];
const canvas=$("scene"), ctx=canvas.getContext("2d"), graph=$("graph"), gx=graph.getContext("2d");
const valid=p=>p && p.length===3 && p.every(Number.isFinite);
function status(message,error=false){$("status").textContent=message;$("status").classList.toggle("error",error);}
function orient(p){return $("up").value==="y"?[p[0],-p[2],p[1]]:$("up").value==="x"?[p[1],p[2],p[0]]:p;}
function fit(){if(!trial)return;let lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];for(const points of trial.xyz)for(const raw of points){if(!valid(raw))continue;const p=orient(raw);for(let j=0;j<3;j++){lo[j]=Math.min(lo[j],p[j]);hi[j]=Math.max(hi[j],p[j]);}}center=lo.map((v,j)=>(v+hi[j])/2);span=Math.max(...hi.map((v,j)=>v-lo[j]),.01);zoom=1;pan=[0,0];draw();}
function project(raw){const p=orient(raw).map((v,j)=>v-center[j]);const x=Math.cos(yaw)*p[0]-Math.sin(yaw)*p[1],depth=Math.sin(yaw)*p[0]+Math.cos(yaw)*p[1];const z=Math.cos(pitch)*p[2]-Math.sin(pitch)*depth;const s=Math.min(canvas.clientWidth,canvas.clientHeight)*.75/span*zoom;return [canvas.clientWidth/2+x*s+pan[0],canvas.clientHeight/2-z*s+pan[1],depth];}
function line(a,b,color,width=1){const p=project(a),q=project(b);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(p[0],p[1]);ctx.lineTo(q[0],q[1]);ctx.stroke();}
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);if(!trial)return;const pts=trial.xyz[frame],a=Number($("marker-a").value),b=Number($("marker-b").value);
// Lab axes retain their original meaning regardless of the selected view-up axis.
const origin=[0,0,0];for(let i=0;i<3;i++){const end=[0,0,0];end[i]=span*.22;line(origin,end,["#ef8686","#82d99d","#7faeeb"][i],2);const p=project(end);ctx.fillStyle=["#ef8686","#82d99d","#7faeeb"][i];ctx.font="12px system-ui";ctx.fillText("XYZ"[i],p[0]+5,p[1]);}
if($("trail").checked){for(let f=Math.max(1,frame-100);f<=frame;f++){const p=trial.xyz[f-1][a],q=trial.xyz[f][a];if(valid(p)&&valid(q))line(p,q,"#357c78",1.5);}}
if(valid(pts[a])&&valid(pts[b]))line(pts[a],pts[b],"#f2c875",2);
const visible=pts.map((p,i)=>({p,i})).filter(v=>valid(v.p)).map(v=>({...v,q:project(v.p)})).sort((a,b)=>b.q[2]-a.q[2]);
for(const {i,q} of visible){ctx.beginPath();ctx.arc(q[0],q[1],i===a||i===b?5:3,0,Math.PI*2);ctx.fillStyle=i===a?"#59dec3":i===b?"#f2c875":"#9bbed7";ctx.fill();if($("labels").checked){ctx.fillStyle="#adbdcd";ctx.font="11px system-ui";ctx.fillText(trial.labels[i],q[0]+7,q[1]-5);}}
$("frame").textContent=`${frame+1} / ${trial.xyz.length} · ${(frame/trial.rate_hz).toFixed(3)} s`;$("timeline").value=String(frame);const d=distances[frame];$("distance").textContent=Number.isFinite(d)?`${d.toFixed(4)} m`:"Ausente";drawGraph();}
function drawGraph(){const w=graph.clientWidth,h=graph.clientHeight;gx.clearRect(0,0,w,h);let lo=Infinity,hi=-Infinity;for(const d of distances)if(Number.isFinite(d)){lo=Math.min(lo,d);hi=Math.max(hi,d);}if(!Number.isFinite(lo))return;const extent=Math.max(hi-lo,.001);gx.strokeStyle="#59dec3";gx.lineWidth=1.5;gx.beginPath();let started=false;distances.forEach((d,i)=>{if(!Number.isFinite(d)){started=false;return;}const x=50+i*(w-65)/Math.max(1,distances.length-1),y=h-16-(d-lo)*(h-34)/extent;if(started)gx.lineTo(x,y);else gx.moveTo(x,y);started=true;});gx.stroke();gx.fillStyle="#8298ad";gx.font="10px system-ui";gx.fillText(`${hi.toFixed(3)} m`,0,14);gx.fillText(`${lo.toFixed(3)} m`,0,h-13);const x=50+frame*(w-65)/Math.max(1,distances.length-1);gx.strokeStyle="#f2c875";gx.beginPath();gx.moveTo(x,0);gx.lineTo(x,h);gx.stroke();}
function measure(){if(!trial)return;const a=Number($("marker-a").value),b=Number($("marker-b").value);distances=trial.xyz.map(p=>valid(p[a])&&valid(p[b])?Math.hypot(...p[a].map((v,j)=>v-p[b][j])):NaN);draw();}
function pause(){playing=false;$("play").textContent="Reproduzir";elapsed=0;}
function load(data){trial=data;frame=0;pause();$("title").textContent=data.name;$("meta").textContent=`${data.xyz.length} quadros · ${data.labels.length} marcadores · ${data.rate_hz} Hz · coordenadas em metros`;$("welcome").hidden=true;for(const key of ["marker-a","marker-b"]){$(key).replaceChildren(...data.labels.map((label,i)=>{const o=document.createElement("option");o.value=String(i);o.textContent=label;return o;}));}$("marker-b").value=String(Math.min(1,data.labels.length-1));for(const id of ["play","prev","next","timeline","export","snapshot"])$(id).disabled=false;$("timeline").max=String(data.xyz.length-1);fit();measure();status("Arquivo carregado. Medidas em metros; quadros ausentes são preservados.");}
function resize(){for(const c of [canvas,graph]){const ratio=window.devicePixelRatio||1;c.width=Math.round(c.clientWidth*ratio);c.height=Math.round(c.clientHeight*ratio);c.getContext("2d").setTransform(ratio,0,0,ratio,0,0);}draw();}
new ResizeObserver(resize).observe($("workspace"));
$("play").onclick=()=>{if(!trial)return;if(playing)pause();else{if(frame===trial.xyz.length-1)frame=0;playing=true;lastTick=performance.now();$("play").textContent="Pausar";}};
function step(delta){if(!trial)return;pause();frame=Math.max(0,Math.min(trial.xyz.length-1,frame+delta));draw();}
$("prev").onclick=()=>step(-1);$("next").onclick=()=>step(1);$("timeline").oninput=()=>{pause();frame=Number($("timeline").value);draw();};
function tick(now){if(playing&&trial){elapsed+=(now-lastTick)/1000*trial.rate_hz*Number($("speed").value);const advance=Math.floor(elapsed);elapsed-=advance;if(advance){frame+=advance;if(frame>=trial.xyz.length){if($("loop").checked)frame%=trial.xyz.length;else{frame=trial.xyz.length-1;pause();}}draw();}}lastTick=now;requestAnimationFrame(tick);}requestAnimationFrame(tick);
let drag=null;canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag[0],dy=e.clientY-drag[1];if(e.shiftKey){pan[0]+=dx;pan[1]+=dy;}else{yaw+=dx*.008;pitch=Math.max(-Math.PI/2,Math.min(Math.PI/2,pitch+dy*.008));}drag=[e.clientX,e.clientY];draw();};canvas.onpointerup=()=>drag=null;canvas.onpointercancel=()=>drag=null;canvas.onwheel=e=>{e.preventDefault();zoom=Math.max(.1,Math.min(20,zoom*Math.exp(-e.deltaY*.001)));draw();};
$("front").onclick=()=>{yaw=0;pitch=0;draw();};$("side").onclick=()=>{yaw=Math.PI/2;pitch=0;draw();};$("top").onclick=()=>{yaw=0;pitch=Math.PI/2;draw();};$("reset").onclick=fit;$("up").onchange=fit;for(const id of ["labels","trail"])$(id).onchange=draw;for(const id of ["marker-a","marker-b"])$(id).onchange=measure;
document.addEventListener("keydown",e=>{if(["INPUT","SELECT","BUTTON","TEXTAREA"].includes(document.activeElement.tagName))return;if(e.code==="Space"){e.preventDefault();$("play").click();}if(e.code==="ArrowLeft")step(-1);if(e.code==="ArrowRight")step(1);});
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$("export").onclick=()=>{const rows=["frame,time_s,distance_m"];distances.forEach((d,i)=>rows.push(`${i},${i/trial.rate_hz},${Number.isFinite(d)?d:""}`));download(rows.join("\n")+"\n","distance.csv","text/csv");};
$("snapshot").onclick=()=>{const root=document.documentElement.cloneNode(true);root.querySelector("#trial-data").textContent=JSON.stringify({server:false,trial}).replace(/</g,"\\u003c");download("<!doctype html>\n"+root.outerHTML,"movement.html","text/html");};
$("open-panel").hidden=!boot.server;
$("file").onchange=async()=>{const file=$("file").files[0];if(!file)return;pause();status("Carregando movimento…");$("file").disabled=true;try{const params=new URLSearchParams({name:file.name,rate:$("rate").value,units:$("units").value});const response=await fetch(`/api/trial?${params}`,{method:"POST",headers:{"Authorization":`Bearer ${token}`,"Content-Type":"application/octet-stream"},body:file});const data=await response.json();if(!response.ok)throw new Error(data.error||"Não foi possível abrir o arquivo.");load(data);}catch(error){status(error.message,true);}finally{$("file").disabled=false;$("file").value="";}};
if(boot.trial)load(boot.trial);resize();
